name: Sync Fork

on:
  schedule:
    - cron: '0 0 * * *' # 每天北京时间早上 8点自动运行
  workflow_dispatch: # 允许你手动点击按钮触发同步

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout target repo
        uses: actions/checkout@v3

      - name: Sync upstream
        uses: aormsby/Fork-Sync-With-Upstream-action@v3.4.1
        with:
          target_repo_token: ${{ secrets.GITHUB_TOKEN }}
          upstream_repository: libaxuan/cursor2api-go
          upstream_branch: main
          target_branch: main
          test_mode: false
